// Generated by scripts/build-nuvio-spec.ts from nuvio-public-api.json.
// Do not edit: run `bun run nuvio:spec`. `bun run nuvio:spec:check` fails in
// CI when this file is stale.

/** Delete library items : `POST /rest/v1/rpc/sync_delete_library_items` */
export type DeleteLibraryItemsRequest = {
	/** Profile index */
	p_profile_id?: number;
	/** Stable installation identifier attached to emitted sync events */
	p_origin_client_id?: string | null;
	/** Exact library identities to delete */
	p_keys: Array<{
		content_id?: string;
		content_type?: "movie" | "series";
	}>;
};

/** Delete library items : `POST /rest/v1/rpc/sync_delete_library_items` */
export type DeleteLibraryItemsResponse = void;

/** Delete profile data : `POST /rest/v1/rpc/sync_delete_profile_data` */
export type DeleteProfileDataRequest = {
	p_profile_id?: number;
};

/** Delete profile data : `POST /rest/v1/rpc/sync_delete_profile_data` */
export type DeleteProfileDataResponse = void;

/** Delete watch history : `POST /rest/v1/rpc/sync_delete_watched_items` */
export type DeleteWatchHistoryRequest = {
	p_profile_id?: number;
	p_keys?: Array<{
		/** Content identifier */
		content_id: string;
		/** Required for series episodes */
		season?: number;
		/** Required for series episodes */
		episode?: number;
	}>;
};

/** Delete watch history : `POST /rest/v1/rpc/sync_delete_watched_items` */
export type DeleteWatchHistoryResponse = void;

/** Get collections : `POST /rest/v1/rpc/sync_pull_collections` */
export type GetCollectionsRequest = {
	p_profile_id?: number;
};

/** Get collections : `POST /rest/v1/rpc/sync_pull_collections` */
export type GetCollectionsResponse = Array<{
	profile_id: number;
	collections_json: Array<{
		/** Unique collection ID */
		id: string;
		/** Collection name */
		title: string;
		/** Optional backdrop image */
		backdropImageUrl: string;
		/** Pin to top of home screen */
		pinToTop: boolean;
		/** `TABBED_GRID`, `ROWS`, or `FOLLOW_LAYOUT` */
		viewMode: "TABBED_GRID" | "ROWS" | "FOLLOW_LAYOUT";
		/** Show "All" tab in tabbed view */
		showAllTab: boolean;
		/** Array of folder objects */
		folders: Array<{
			/** Unique folder ID */
			id: string;
			/** Folder name */
			title: string;
			/** Optional cover image */
			coverImageUrl: string;
			/** Optional emoji icon */
			coverEmoji: string;
			/** `POSTER`, `LANDSCAPE`, or `SQUARE` */
			tileShape: "POSTER" | "LANDSCAPE" | "SQUARE";
			/** Hide the tile title text */
			hideTitle: boolean;
			/** Array of catalog references */
			catalogSources: Array<{
				/** Addon identifier */
				addonId: string;
				/** Content type (e.g. `movie`, `series`) */
				type: string;
				/** Catalog identifier */
				catalogId: string;
			}>;
		}>;
	}>;
	updated_at: string;
}>;

/** Get current user : `GET /auth/v1/user` */
export type GetCurrentUserRequest = never;

/** Get current user : `GET /auth/v1/user` */
export type GetCurrentUserResponse = {
	id: string;
	email: string;
	created_at: string;
};

/** Get home catalog settings : `POST /rest/v1/rpc/sync_pull_home_catalog_settings` */
export type GetHomeCatalogSettingsRequest = {
	p_profile_id?: number;
	p_platform?: string;
};

/** Get home catalog settings : `POST /rest/v1/rpc/sync_pull_home_catalog_settings` */
export type GetHomeCatalogSettingsResponse = Array<{
	id: string;
	user_id: string;
	profile_id: number;
	platform: string;
	settings_json: {
		rows: unknown[];
		hidden_catalogs: unknown[];
	};
	updated_at: string;
}>;

/** Get library : `POST /rest/v1/rpc/sync_pull_library` */
export type GetLibraryRequest = {
	/** Profile index */
	p_profile_id?: number;
	/** Max items per page */
	p_limit?: number;
	/** Pagination offset */
	p_offset?: number;
};

/** Get library : `POST /rest/v1/rpc/sync_pull_library` */
export type GetLibraryResponse = Array<{
	id: string;
	user_id: string;
	profile_id: number;
	/** Content identifier (e.g. `tmdb:550`) */
	content_id: string;
	/** `movie` or `series` */
	content_type: "movie" | "series";
	/** Content title */
	name: string;
	/** Poster image URL */
	poster: string | null;
	/** `POSTER`, `LANDSCAPE`, or `SQUARE` */
	poster_shape: "POSTER" | "LANDSCAPE" | "SQUARE";
	/** Background image URL */
	background: string | null;
	/** Synopsis */
	description: string | null;
	/** Year or year range */
	release_info: string | null;
	/** IMDb rating */
	imdb_rating: number | null;
	/** Genre list */
	genres: string[];
	/** Related addon URL */
	addon_base_url: string | null;
	/** Epoch milliseconds when added */
	added_at: number;
	created_at: string;
	updated_at: string;
}>;

/** Get library delta : `POST /rest/v1/rpc/sync_pull_library_delta` */
export type GetLibraryDeltaRequest = {
	/** Profile index */
	p_profile_id?: number;
	/** Return events with an ID greater than this cursor */
	p_since_event_id?: number;
	/** Page size, clamped to `1..1000` */
	p_limit?: number;
};

/** Get library delta : `POST /rest/v1/rpc/sync_pull_library_delta` */
export type GetLibraryDeltaResponse = Array<{
	/** Monotonically increasing cursor */
	event_id: number;
	/** `upsert` or `delete` */
	operation: "upsert" | "delete";
	content_id: string;
	content_type: "movie" | "series";
	name: string;
	poster: string | null;
	poster_shape: "POSTER" | "LANDSCAPE" | "SQUARE";
	background: string | null;
	description: string | null;
	release_info: string | null;
	imdb_rating: number | null;
	genres: string[];
	addon_base_url: string | null;
	added_at: number;
}>;

/** Get library delta cursor : `POST /rest/v1/rpc/sync_get_library_delta_cursor` */
export type GetLibraryDeltaCursorRequest = {
	/** Profile index */
	p_profile_id?: number;
};

/** Get library delta cursor : `POST /rest/v1/rpc/sync_get_library_delta_cursor` */
export type GetLibraryDeltaCursorResponse = number;

/** Get settings : `POST /rest/v1/rpc/sync_pull_profile_settings_blob` */
export type GetSettingsRequest = {
	/** Profile index */
	p_profile_id: number;
	/** Optional platform namespace. Recommended for new clients. */
	p_platform?: string;
};

/** Get settings : `POST /rest/v1/rpc/sync_pull_profile_settings_blob` */
export type GetSettingsResponse = Array<{
	profile_id: number;
	settings_json: {
		theme: string;
		player_quality: string;
		subtitle_language: string;
		auto_play_next: boolean;
	};
	updated_at: string;
}>;

/** Get watch history : `POST /rest/v1/rpc/sync_pull_watched_items` */
export type GetWatchHistoryRequest = {
	/** Profile index */
	p_profile_id?: number;
	/** Page number (1-indexed) */
	p_page?: number;
	/** Items per page */
	p_page_size?: number;
};

/** Get watch history : `POST /rest/v1/rpc/sync_pull_watched_items` */
export type GetWatchHistoryResponse = Array<{
	id: string;
	user_id: string;
	profile_id: number;
	/** Content identifier */
	content_id: string;
	/** `movie` or `series` */
	content_type: "movie" | "series";
	/** Content title */
	title: string;
	/** Season number (series only) */
	season: number | null;
	/** Episode number (series only) */
	episode: number | null;
	/** Epoch milliseconds */
	watched_at: number;
	created_at: string;
}>;

/** Get watch history delta : `POST /rest/v1/rpc/sync_pull_watched_items_delta` */
export type GetWatchHistoryDeltaRequest = {
	/** Profile index */
	p_profile_id?: number;
	/** Return events with `event_id` greater than this value */
	p_since_event_id?: number;
	/** Max events to return, capped at `1000` */
	p_limit?: number;
};

/** Get watch history delta : `POST /rest/v1/rpc/sync_pull_watched_items_delta` */
export type GetWatchHistoryDeltaResponse = Array<{
	event_id: number;
	operation: "upsert" | "delete";
	content_id: string;
	content_type: "movie" | "series";
	title: string;
	season: null | number;
	episode: null | number;
	watched_at: number;
}>;

/** Get watch history delta cursor : `POST /rest/v1/rpc/sync_get_watched_items_delta_cursor` */
export type GetWatchHistoryDeltaCursorRequest = {
	p_profile_id?: number;
};

/** Get watch history delta cursor : `POST /rest/v1/rpc/sync_get_watched_items_delta_cursor` */
export type GetWatchHistoryDeltaCursorResponse = number;

/** Get watch progress : `POST /rest/v1/rpc/sync_pull_watch_progress` */
export type GetWatchProgressRequest = {
	/** Profile index */
	p_profile_id?: number;
	/** Optional epoch-millisecond cursor. When set, returns rows with `last_watched` greater than this value. */
	p_since_last_watched?: number;
	/** Optional row limit. Without `p_since_last_watched`, the server caps the result at 200 rows. */
	p_limit?: number;
};

/** Get watch progress : `POST /rest/v1/rpc/sync_pull_watch_progress` */
export type GetWatchProgressResponse = Array<{
	id: string;
	user_id: string;
	profile_id: number;
	/** Content identifier (e.g. `tmdb:550`) */
	content_id: string;
	/** `movie` or `series` */
	content_type: "movie" | "series";
	/** Specific playback item ID */
	video_id: string;
	/** Season number (series only) */
	season: number | null;
	/** Episode number (series only) */
	episode: number | null;
	/** Unique key (see [Progress Key Format](#progress-key-format)) */
	progress_key: string;
	/** Playback position in milliseconds */
	position: number;
	/** Total duration in milliseconds */
	duration: number;
	/** Epoch milliseconds of last playback */
	last_watched: number;
}>;

/** Get watch progress delta : `POST /rest/v1/rpc/sync_pull_watch_progress_delta` */
export type GetWatchProgressDeltaRequest = {
	/** Profile index */
	p_profile_id?: number;
	/** Return events with `event_id` greater than this value */
	p_since_event_id?: number;
	/** Max events to return, capped at `1000` */
	p_limit?: number;
};

/** Get watch progress delta : `POST /rest/v1/rpc/sync_pull_watch_progress_delta` */
export type GetWatchProgressDeltaResponse = Array<{
	event_id: number;
	operation: "upsert" | "delete";
	progress_key: string;
	content_id: string;
	content_type: "movie" | "series";
	video_id: string;
	season: null | number;
	episode: null | number;
	position: number;
	duration: number;
	last_watched: number;
}>;

/** Get watch progress delta cursor : `POST /rest/v1/rpc/sync_get_watch_progress_delta_cursor` */
export type GetWatchProgressDeltaCursorRequest = {
	p_profile_id?: number;
};

/** Get watch progress delta cursor : `POST /rest/v1/rpc/sync_get_watch_progress_delta_cursor` */
export type GetWatchProgressDeltaCursorResponse = number;

/** Health check : `GET /functions/v1/health-check` */
export type HealthCheckRequest = never;

/** Health check : `GET /functions/v1/health-check` */
export type HealthCheckResponse = {
	status: string;
	database: string;
	latency_ms: number;
	timestamp: string;
};

/** Health check : `POST /rest/v1/rpc/health_ping` */
export type HealthPingRequest = never;

/** Health check : `POST /rest/v1/rpc/health_ping` */
export type HealthPingResponse = void;

/** List addons : `GET /rest/v1/addons` */
export type ListAddonsRequest = never;

/** List addons : `GET /rest/v1/addons` */
export type ListAddonsResponse = Array<{
	/** Record ID */
	id: string;
	/** Owner user ID */
	user_id: string;
	/** Profile index (1 to 6 in the public client surface) */
	profile_id: number;
	/** Addon manifest URL */
	url: string;
	/** Display name */
	name: string | null;
	/** Whether addon is active */
	enabled: boolean;
	/** Display order (0-based) */
	sort_order: number;
	/** Creation time */
	created_at: string;
	/** Last update time */
	updated_at: string;
}>;

/** List avatars : `POST /rest/v1/rpc/get_avatar_catalog` */
export type ListAvatarsRequest = never;

/** List avatars : `POST /rest/v1/rpc/get_avatar_catalog` */
export type ListAvatarsResponse = Array<{
	/** Avatar ID for use in profile `avatar_id` */
	id: string;
	/** Human-readable name */
	display_name: string;
	/** Storage path for the image */
	storage_path: string;
	/** Category (e.g. `character`) */
	category: string;
	/** Display order */
	sort_order: number;
	/** Whether available for selection */
	is_active: boolean;
	/** Suggested background color */
	bg_color: string | null;
	created_at: string;
}>;

/** List profiles : `POST /rest/v1/rpc/sync_pull_profiles` */
export type ListProfilesRequest = never;

/** List profiles : `POST /rest/v1/rpc/sync_pull_profiles` */
export type ListProfilesResponse = Array<{
	/** Profile record ID */
	id: string;
	/** Owner user ID */
	user_id: string;
	/** 1 to 6, unique per user in the public client surface */
	profile_index: number;
	/** Display name */
	name: string;
	/** Hex color (e.g. `#1E88E5`) */
	avatar_color_hex: string;
	/** Whether this profile shares addons with profile 1 */
	uses_primary_addons: boolean;
	/** Reference to avatar catalog entry */
	avatar_id: string | null;
	/** Custom profile avatar image URL */
	avatar_url: string | null;
	/** Read-only lock state for clients that need to show locked profiles */
	pin_enabled: boolean;
	/** Read-only lock expiry, if the profile is temporarily locked */
	pin_locked_until: string | null;
	/** Creation time */
	created_at: string;
	/** Last update time */
	updated_at: string;
}>;

/** Refresh token : `POST /auth/v1/token?grant_type=refresh_token` */
export type RefreshTokenRequest = {
	refresh_token?: string;
};

/** Refresh token : `POST /auth/v1/token?grant_type=refresh_token` */
export type RefreshTokenResponse = void;

/** Sign in (email/password) : `POST /auth/v1/token?grant_type=password` */
export type SignInEmailPasswordRequest = {
	email?: string;
	password?: string;
};

/** Sign in (email/password) : `POST /auth/v1/token?grant_type=password` */
export type SignInEmailPasswordResponse = void;

/** Sign out : `POST /auth/v1/logout` */
export type SignOutRequest = never;

/** Sign out : `POST /auth/v1/logout` */
export type SignOutResponse = void;

/** Sign up (email/password) : `POST /auth/v1/signup` */
export type SignUpEmailPasswordRequest = {
	email?: string;
	password?: string;
};

/** Sign up (email/password) : `POST /auth/v1/signup` */
export type SignUpEmailPasswordResponse = {
	access_token: string;
	token_type: string;
	expires_in: number;
	refresh_token: string;
	user: {
		id: string;
		email: string;
		created_at: string;
	};
};

/** Supporter Wall : `GET /api/supporters/wall` */
export type SupporterWallRequest = never;

/** Supporter Wall : `GET /api/supporters/wall` */
export type SupporterWallResponse = {
	top: {
		members: Array<{
			displayName: string;
			avatarUrl: string;
			membershipLevel: string;
			supporterSince: string;
		}>;
		totalCount: number;
	};
	recent: {
		members: unknown[];
		totalCount: number;
	};
	pagination: {
		limit: number;
		offset: number;
	};
};

/** Sync addons (push) : `POST /rest/v1/rpc/sync_push_addons` */
export type SyncAddonsPushRequest = {
	p_profile_id?: number;
	p_addons?: Array<{
		/** Addon manifest URL */
		url: string;
		/** Display name */
		name?: string;
		/** Default `true` */
		enabled?: boolean;
		/** Display order, default `0` */
		sort_order?: number;
	}>;
};

/** Sync addons (push) : `POST /rest/v1/rpc/sync_push_addons` */
export type SyncAddonsPushResponse = void;

/** Delete watch progress (single) / Delete watch progress (batch) : `POST /rest/v1/rpc/sync_delete_watch_progress` */
export type SyncDeleteWatchProgressRequest = {
	p_progress_key?: string;
	p_profile_id?: number;
} | {
	p_keys?: string[];
	p_profile_id?: number;
};

/** Delete watch progress (single) / Delete watch progress (batch) : `POST /rest/v1/rpc/sync_delete_watch_progress` */
export type SyncDeleteWatchProgressResponse = void;

/** Sync library (push): legacy full replace : `POST /rest/v1/rpc/sync_push_library` */
export type SyncLibraryPushLegacyFullReplaceRequest = {
	p_profile_id?: number;
	p_items?: Array<{
		content_id?: string;
		content_type?: "movie" | "series";
		name?: string;
		poster?: string;
		poster_shape?: "POSTER" | "LANDSCAPE" | "SQUARE";
		background?: string;
		description?: string;
		release_info?: string;
		imdb_rating?: number;
		genres?: string[];
		addon_base_url?: string;
		added_at?: number;
	}>;
};

/** Sync library (push): legacy full replace : `POST /rest/v1/rpc/sync_push_library` */
export type SyncLibraryPushLegacyFullReplaceResponse = void;

/** Sync overview : `POST /rest/v1/rpc/get_sync_overview` */
export type SyncOverviewRequest = never;

/** Sync overview : `POST /rest/v1/rpc/get_sync_overview` */
export type SyncOverviewResponse = {
	addons: Record<string, number>;
	library_items: Record<string, number>;
	watch_progress: Record<string, number>;
	watched_items: Record<string, number>;
	profiles: Record<string, {
		name: string;
		color: string;
	}>;
};

/** Sync watch history (push) : `POST /rest/v1/rpc/sync_push_watched_items` */
export type SyncWatchHistoryPushRequest = {
	p_profile_id?: number;
	p_items?: Array<{
		/** Content identifier */
		content_id: string;
		/** `movie` or `series` */
		content_type: "movie" | "series";
		/** Title */
		title?: string;
		/** Epoch milliseconds */
		watched_at: number;
		/** Season number */
		season?: number;
		/** Episode number */
		episode?: number;
	}>;
};

/** Sync watch history (push) : `POST /rest/v1/rpc/sync_push_watched_items` */
export type SyncWatchHistoryPushResponse = void;

/** Sync watch progress (push) : `POST /rest/v1/rpc/sync_push_watch_progress` */
export type SyncWatchProgressPushRequest = {
	p_profile_id?: number;
	p_entries?: Array<{
		/** Content identifier */
		content_id: string;
		/** `movie` or `series` */
		content_type: "movie" | "series";
		/** Playback item identifier */
		video_id: string;
		/** Playback position in ms */
		position: number;
		/** Total duration in ms */
		duration: number;
		/** Epoch milliseconds */
		last_watched: number;
		/** Season number (for series) */
		season?: number;
		/** Episode number (for series) */
		episode?: number;
	}>;
};

/** Sync watch progress (push) : `POST /rest/v1/rpc/sync_push_watch_progress` */
export type SyncWatchProgressPushResponse = void;

/** Update collections : `POST /rest/v1/rpc/sync_push_collections` */
export type UpdateCollectionsRequest = {
	p_profile_id?: number;
	p_collections_json?: Array<{
		id?: string;
		title?: string;
		viewMode?: "TABBED_GRID" | "ROWS" | "FOLLOW_LAYOUT";
		folders?: unknown[];
	}>;
};

/** Update collections : `POST /rest/v1/rpc/sync_push_collections` */
export type UpdateCollectionsResponse = void;

/** Update home catalog settings : `POST /rest/v1/rpc/sync_push_home_catalog_settings` */
export type UpdateHomeCatalogSettingsRequest = {
	/** Profile index */
	p_profile_id: number;
	/** Optional platform namespace. Recommended for new clients. */
	p_platform?: string;
	/** Full home catalog settings payload */
	p_settings_json: {
		rows?: unknown[];
		hidden_catalogs?: unknown[];
	};
};

/** Update home catalog settings : `POST /rest/v1/rpc/sync_push_home_catalog_settings` */
export type UpdateHomeCatalogSettingsResponse = void;

/** Update profiles : `POST /rest/v1/rpc/sync_push_profiles` */
export type UpdateProfilesRequest = {
	/** Highest profile slot this client manages. Use `6` for current public clients. Defaults to `4` when omitted. */
	p_client_max_profiles?: number;
	/** Complete profile list for the declared profile range */
	p_profiles: Array<{
		/** 1 to 6 in the public client surface */
		profile_index: number;
		/** Display name */
		name: string;
		/** Hex color code */
		avatar_color_hex?: string;
		/** Share addons with profile 1 */
		uses_primary_addons?: boolean;
		/** Avatar catalog ID; existing value is kept if omitted or null and `avatar_url` is not provided */
		avatar_id?: string;
		/** Custom avatar image URL. When provided, it takes precedence over `avatar_id`; send `null` or `""` to clear it. */
		avatar_url?: string | null;
	}>;
};

/** Update profiles : `POST /rest/v1/rpc/sync_push_profiles` */
export type UpdateProfilesResponse = void;

/** Update settings : `POST /rest/v1/rpc/sync_push_profile_settings_blob` */
export type UpdateSettingsRequest = {
	p_profile_id?: number;
	p_platform?: string;
	p_settings_json?: {
		theme?: string;
		player_quality?: string;
		subtitle_language?: string;
		auto_play_next?: boolean;
	};
};

/** Update settings : `POST /rest/v1/rpc/sync_push_profile_settings_blob` */
export type UpdateSettingsResponse = void;

/** Upsert library items : `POST /rest/v1/rpc/sync_push_library_items` */
export type UpsertLibraryItemsRequest = {
	/** Profile index */
	p_profile_id?: number;
	/** Stable installation identifier attached to emitted sync events */
	p_origin_client_id?: string | null;
	/** Items to insert or update */
	p_items: Array<{
		content_id?: string;
		content_type?: "movie" | "series";
		name?: string;
		poster?: string;
		poster_shape?: "POSTER" | "LANDSCAPE" | "SQUARE";
		background?: string;
		description?: string;
		release_info?: string;
		imdb_rating?: number;
		genres?: string[];
		addon_base_url?: string;
		added_at?: number;
	}>;
};

/** Upsert library items : `POST /rest/v1/rpc/sync_push_library_items` */
export type UpsertLibraryItemsResponse = void;

/** Every operation, by `operationId`. */
export interface NuvioOperations {
	deleteLibraryItems: { request: DeleteLibraryItemsRequest; response: DeleteLibraryItemsResponse };
	deleteProfileData: { request: DeleteProfileDataRequest; response: DeleteProfileDataResponse };
	deleteWatchHistory: { request: DeleteWatchHistoryRequest; response: DeleteWatchHistoryResponse };
	getCollections: { request: GetCollectionsRequest; response: GetCollectionsResponse };
	getCurrentUser: { request: GetCurrentUserRequest; response: GetCurrentUserResponse };
	getHomeCatalogSettings: { request: GetHomeCatalogSettingsRequest; response: GetHomeCatalogSettingsResponse };
	getLibrary: { request: GetLibraryRequest; response: GetLibraryResponse };
	getLibraryDelta: { request: GetLibraryDeltaRequest; response: GetLibraryDeltaResponse };
	getLibraryDeltaCursor: { request: GetLibraryDeltaCursorRequest; response: GetLibraryDeltaCursorResponse };
	getSettings: { request: GetSettingsRequest; response: GetSettingsResponse };
	getWatchHistory: { request: GetWatchHistoryRequest; response: GetWatchHistoryResponse };
	getWatchHistoryDelta: { request: GetWatchHistoryDeltaRequest; response: GetWatchHistoryDeltaResponse };
	getWatchHistoryDeltaCursor: { request: GetWatchHistoryDeltaCursorRequest; response: GetWatchHistoryDeltaCursorResponse };
	getWatchProgress: { request: GetWatchProgressRequest; response: GetWatchProgressResponse };
	getWatchProgressDelta: { request: GetWatchProgressDeltaRequest; response: GetWatchProgressDeltaResponse };
	getWatchProgressDeltaCursor: { request: GetWatchProgressDeltaCursorRequest; response: GetWatchProgressDeltaCursorResponse };
	healthCheck: { request: HealthCheckRequest; response: HealthCheckResponse };
	healthPing: { request: HealthPingRequest; response: HealthPingResponse };
	listAddons: { request: ListAddonsRequest; response: ListAddonsResponse };
	listAvatars: { request: ListAvatarsRequest; response: ListAvatarsResponse };
	listProfiles: { request: ListProfilesRequest; response: ListProfilesResponse };
	refreshToken: { request: RefreshTokenRequest; response: RefreshTokenResponse };
	signInEmailPassword: { request: SignInEmailPasswordRequest; response: SignInEmailPasswordResponse };
	signOut: { request: SignOutRequest; response: SignOutResponse };
	signUpEmailPassword: { request: SignUpEmailPasswordRequest; response: SignUpEmailPasswordResponse };
	supporterWall: { request: SupporterWallRequest; response: SupporterWallResponse };
	syncAddonsPush: { request: SyncAddonsPushRequest; response: SyncAddonsPushResponse };
	syncDeleteWatchProgress: { request: SyncDeleteWatchProgressRequest; response: SyncDeleteWatchProgressResponse };
	syncLibraryPushLegacyFullReplace: { request: SyncLibraryPushLegacyFullReplaceRequest; response: SyncLibraryPushLegacyFullReplaceResponse };
	syncOverview: { request: SyncOverviewRequest; response: SyncOverviewResponse };
	syncWatchHistoryPush: { request: SyncWatchHistoryPushRequest; response: SyncWatchHistoryPushResponse };
	syncWatchProgressPush: { request: SyncWatchProgressPushRequest; response: SyncWatchProgressPushResponse };
	updateCollections: { request: UpdateCollectionsRequest; response: UpdateCollectionsResponse };
	updateHomeCatalogSettings: { request: UpdateHomeCatalogSettingsRequest; response: UpdateHomeCatalogSettingsResponse };
	updateProfiles: { request: UpdateProfilesRequest; response: UpdateProfilesResponse };
	updateSettings: { request: UpdateSettingsRequest; response: UpdateSettingsResponse };
	upsertLibraryItems: { request: UpsertLibraryItemsRequest; response: UpsertLibraryItemsResponse };
}
