import { describe, expect, it } from "vitest";
import { enumFromDescription, inferEnums } from "./enums.ts";
import type { OpenApiDocument } from "./openapi.ts";
import { renderTypes, typeOf } from "./typescript.ts";

describe("enumFromDescription", () => {
	it("reads a description that is only a list of values", () => {
		expect(enumFromDescription("`movie` or `series`")).toEqual([
			"movie",
			"series",
		]);
		expect(enumFromDescription("`POSTER`, `LANDSCAPE`, or `SQUARE`")).toEqual([
			"POSTER",
			"LANDSCAPE",
			"SQUARE",
		]);
	});

	// "e.g." lists are examples, not the whole set.
	it("leaves examples and prose alone", () => {
		expect(
			enumFromDescription("Content type (e.g. `movie`, `series`)"),
		).toBeNull();
		expect(enumFromDescription("Hex color (e.g. `#1E88E5`)")).toBeNull();
		expect(enumFromDescription("`movie`")).toBeNull();
		expect(enumFromDescription(undefined)).toBeNull();
	});
});

function doc(
	request: Record<string, unknown>,
	response: Record<string, unknown>,
): OpenApiDocument {
	return {
		openapi: "3.1.0",
		"x-generated-by": "test",
		info: { title: "t", version: "1" },
		servers: [],
		tags: [],
		components: { securitySchemes: {} },
		paths: {
			"/rpc/push": {
				post: {
					operationId: "pushThing",
					summary: "Push a thing",
					tags: [],
					security: [],
					requestBody: {
						required: true,
						content: { "application/json": { schema: request } },
					},
					responses: {
						"200": {
							description: "ok",
							content: { "application/json": { schema: response } },
						},
					},
				},
			},
		},
	} as OpenApiDocument;
}

describe("inferEnums", () => {
	it("applies a set learned in one place to the same field everywhere", () => {
		const document = doc(
			{
				type: "object",
				properties: {
					content_type: { type: "string", description: "`movie` or `series`" },
				},
			},
			{
				type: "array",
				items: {
					type: "object",
					properties: { content_type: { type: ["string", "null"] } },
				},
			},
		);
		inferEnums(document);
		const op = document.paths["/rpc/push"].post;
		const response = op.responses["200"].content?.["application/json"].schema;
		expect(response?.items?.properties?.content_type.enum).toEqual([
			"movie",
			"series",
			null,
		]);
	});

	it("leaves a field alone when the spec lists two different sets for it", () => {
		const document = doc(
			{
				type: "object",
				properties: { kind: { type: "string", description: "`a` or `b`" } },
			},
			{
				type: "object",
				properties: { kind: { type: "string", description: "`c` or `d`" } },
			},
		);
		expect(inferEnums(document)).toEqual({});
	});
});

describe("typeOf", () => {
	it("maps primitives, nullables, enums and arrays", () => {
		expect(typeOf({ type: "integer" }, "response")).toBe("number");
		expect(typeOf({ type: ["string", "null"] }, "response")).toBe(
			"string | null",
		);
		expect(typeOf({ type: "string", enum: ["a", "b"] }, "response")).toBe(
			'"a" | "b"',
		);
		expect(
			typeOf({ type: "array", items: { type: "string" } }, "response"),
		).toBe("string[]");
		expect(typeOf({}, "response")).toBe("unknown");
	});

	// Request fields the API defaults are optional; response fields are all
	// present, since response schemas come from what the API returned.
	it("marks optionality by side", () => {
		const schema = {
			type: "object",
			required: ["a"],
			properties: { a: { type: "string" }, b: { type: "string" } },
		};
		expect(typeOf(schema, "request")).toBe("{\n\ta: string;\n\tb?: string;\n}");
		expect(typeOf(schema, "response")).toBe("{\n\ta: string;\n\tb: string;\n}");
	});

	it("quotes keys that are not identifiers", () => {
		expect(
			typeOf(
				{ type: "object", properties: { "a-b": { type: "string" } } },
				"response",
			),
		).toContain('"a-b": string;');
	});
});

describe("renderTypes", () => {
	it("emits a request / response pair per operation and the operation map", () => {
		const source = renderTypes(
			doc(
				{ type: "object", properties: { p_id: { type: "integer" } } },
				{ type: "array", items: { type: "boolean" } },
			),
		);
		expect(source).toContain("export type PushThingRequest = {");
		expect(source).toContain("export type PushThingResponse = boolean[];");
		expect(source).toContain(
			"\tpushThing: { request: PushThingRequest; response: PushThingResponse };",
		);
		expect(source.startsWith("// Generated by")).toBe(true);
	});
});
