/**
 * OpenAPI document -> TypeScript declarations.
 *
 * One request / response pair per operation, named after its `operationId`
 * (`getLibraryDelta` -> `GetLibraryDeltaRequest`, `GetLibraryDeltaResponse`),
 * plus a `NuvioOperations` map keyed by operation id. `src/lib/nuvio/types.ts`
 * aliases its wire types to these, so a change in the published spec surfaces
 * as a type error at the call sites rather than as a silent mismatch.
 *
 * Which properties are required:
 *
 * - Request bodies: the ones the spec's field tables mark required. The rest
 *   are optional : the API fills in its documented defaults.
 * - Responses: every property. Response schemas are built from the spec's JSON
 *   examples, which is to say from what the API actually returns; a field the
 *   API may leave out is one the example shows as `null`, and that nullability
 *   is carried through.
 */
import type { JsonSchema } from "./json-schema.ts";
import type { OpenApiDocument } from "./openapi.ts";

const HEADER = `// Generated by scripts/build-nuvio-spec.ts from nuvio-public-api.json.
// Do not edit: run \`bun run nuvio:spec\`. \`bun run nuvio:spec:check\` fails in
// CI when this file is stale.
`;

type Side = "request" | "response";

function pascal(operationId: string): string {
	return operationId.charAt(0).toUpperCase() + operationId.slice(1);
}

function literal(value: unknown): string {
	return value === null ? "null" : JSON.stringify(value);
}

/** A property key, quoted only when it has to be. */
function key(name: string): string {
	return /^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name);
}

function comment(description: string | undefined): string {
	if (!description) {
		return "";
	}
	const text = description.replace(/\*\//g, "*\\/").replace(/\s+/g, " ").trim();
	return `/** ${text} */\n`;
}

function primitive(type: string): string {
	switch (type) {
		case "string":
			return "string";
		case "integer":
		case "number":
			return "number";
		case "boolean":
			return "boolean";
		case "null":
			return "null";
		case "array":
			return "unknown[]";
		case "object":
			return "Record<string, unknown>";
		default:
			return "unknown";
	}
}

function union(members: string[]): string {
	const unique = [...new Set(members)];
	return unique.length === 0 ? "unknown" : unique.join(" | ");
}

/**
 * `depth` is the nesting level of the object itself: its properties sit one tab
 * deeper, its closing brace at `depth`.
 */
function objectType(schema: JsonSchema, side: Side, depth: number): string {
	const properties = Object.entries(schema.properties ?? {});
	if (properties.length === 0) {
		return schema.additionalProperties
			? `Record<string, ${typeOf(schema.additionalProperties, side, depth)}>`
			: "Record<string, unknown>";
	}
	const required = new Set(schema.required ?? []);
	const inner = "\t".repeat(depth + 1);
	const lines = properties.map(([name, child]) => {
		const optional = side === "request" && !required.has(name) ? "?" : "";
		const doc = comment(child.description);
		return `${doc ? `${inner}${doc}` : ""}${inner}${key(name)}${optional}: ${typeOf(child, side, depth + 1)};`;
	});
	return `{\n${lines.join("\n")}\n${"\t".repeat(depth)}}`;
}

export function typeOf(schema: JsonSchema, side: Side, depth = 0): string {
	if (schema.const !== undefined) {
		return literal(schema.const);
	}
	if (schema.enum) {
		return union(schema.enum.map(literal));
	}
	if (schema.oneOf) {
		return union(schema.oneOf.map((member) => typeOf(member, side, depth)));
	}
	const types = Array.isArray(schema.type)
		? schema.type
		: schema.type
			? [schema.type]
			: [];
	if (types.length === 0) {
		return schema.properties ? objectType(schema, side, depth) : "unknown";
	}
	return union(
		types.map((type) => {
			if (type === "object") {
				return objectType(schema, side, depth);
			}
			if (type === "array") {
				const item = schema.items
					? typeOf(schema.items, side, depth)
					: "unknown";
				return /[|&{]/.test(item) ? `Array<${item}>` : `${item}[]`;
			}
			return primitive(type);
		}),
	);
}

interface Operation {
	id: string;
	summary: string;
	method: string;
	path: string;
	request: JsonSchema | null;
	response: JsonSchema | null;
}

function operationsOf(document: OpenApiDocument): Operation[] {
	const out: Operation[] = [];
	for (const [path, item] of Object.entries(document.paths)) {
		for (const [method, operation] of Object.entries(item)) {
			const request =
				Object.values(operation.requestBody?.content ?? {})[0]?.schema ?? null;
			const success = Object.entries(operation.responses)
				.filter(([status]) => status.startsWith("2"))
				.sort(([a], [b]) => a.localeCompare(b))
				.map(([, response]) => Object.values(response.content ?? {})[0]?.schema)
				.find(Boolean);
			out.push({
				id: operation.operationId,
				summary: operation.summary,
				method: method.toUpperCase(),
				path,
				request,
				response: success ?? null,
			});
		}
	}
	return out.sort((a, b) => a.id.localeCompare(b.id));
}

/** The whole generated module, ready to write to disk. */
export function renderTypes(document: OpenApiDocument): string {
	const operations = operationsOf(document);
	const blocks = operations.map((operation) => {
		const name = pascal(operation.id);
		const request = operation.request
			? typeOf(operation.request, "request")
			: "never";
		const response = operation.response
			? typeOf(operation.response, "response")
			: "void";
		const doc = `/** ${operation.summary} : \`${operation.method} ${operation.path}\` */\n`;
		return [
			`${doc}export type ${name}Request = ${request};`,
			`${doc}export type ${name}Response = ${response};`,
		].join("\n\n");
	});
	const map = operations
		.map(
			(operation) =>
				`\t${operation.id}: { request: ${pascal(operation.id)}Request; response: ${pascal(operation.id)}Response };`,
		)
		.join("\n");
	return `${HEADER}\n${blocks.join("\n\n")}\n\n/** Every operation, by \`operationId\`. */\nexport interface NuvioOperations {\n${map}\n}\n`;
}
