import { describe, expect, it, vi } from "vitest";

vi.mock("$app/server", () => ({ getRequestEvent: () => ({ locals: {} }) }));
// `$app/env/private` is generated by SvelteKit and is not resolvable under
// vitest; the value it would carry is irrelevant here because the parsing
// rules are tested against `parseAdminEmails` directly.
vi.mock("$app/env/private", () => ({
	NUVIO_ADMIN_EMAILS: "",
	NUVIO_DATA_DIR: "data",
}));

import { isAdminEmail, parseAdminEmails } from "./admin.ts";

// The parsing rules are covered against `parseAdminEmails` rather than the
// environment: reading the real variable would make these pass or fail
// depending on whoever's `.env` is on the machine.
describe("parseAdminEmails", () => {
	it("is empty when the variable is unset, so nobody is an admin by default", () => {
		expect(parseAdminEmails("")).toEqual([]);
	});

	it("splits on commas and whitespace and folds case", () => {
		expect(
			parseAdminEmails(
				" One@Example.com,two@example.com \n THREE@example.com ",
			),
		).toEqual(["one@example.com", "two@example.com", "three@example.com"]);
	});

	it("drops the empty entries a trailing comma leaves behind", () => {
		expect(parseAdminEmails("a@example.com,,")).toEqual(["a@example.com"]);
	});
});

describe("isAdminEmail", () => {
	it("treats a missing email as not an admin", () => {
		expect(isAdminEmail(null)).toBe(false);
		expect(isAdminEmail(undefined)).toBe(false);
		expect(isAdminEmail("")).toBe(false);
	});

	it("rejects an address that cannot be in any allowlist", () => {
		expect(isAdminEmail("nobody@example.invalid")).toBe(false);
	});
});
